routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('trangchu',function()
{
	return view('layouts.index');
});
Route::group(['prefix'=>'/','middleware'=>'admin_login'],function()
{
	Route::resource('user','UserController');
	Route::resource('projects','ProjectController');
	
});
Route::post('login','LoginController@check');
Route::get('login','LoginController@index');
Route::get('logout','LoginController@destroy');

app/Projects.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Projects extends Model
{
    protected $table = "projects";

   	protected $fillable = [
   		'user_id', 'name', 'is_active', 'description', 'sort_order'
   	];

    public function Uptimes()
    {
    	return $this->hasMany('App\Uptimes','id_projects','id');
    }
   public function UptimeData()
   {
   		return $this->hasManyThrough('App\UptimeData','App\Uptimes','id_projects','id_uptimes','id');
   }
   public function User()
   {
      return $this->belongsTo('App\User');
   }

}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Projects;
use Illuminate\Support\Facades\Auth;
use DB;
use Log;
use Validator;
class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $projects = Projects::all();

        return view('projects.index',['projects'=>$projects]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('projects.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $data = $request->all();
        unset($data['_token']);
        DB::beginTransaction();
        try{
            /*$message = [
                'name.required'              =>   'Trường này không được phép để trống',
                'name.max'                   =>   'Tên không được vượt qua 255 ký tự',
                'name.min'                   =>   'Tên không ít hơn 3 ký tự',
                'description.required'       =>   'Trường này không được phép để trống',
                'description.max'            =>   'Tên không được vượt qua 255 ký tự',
                'description.min'            =>   'Tên không ít hơn 3 ký tự',
                'description.string'         =>   'Tên kiểu không chứa ký tự đặc biệt',
                'sort_order.required'        =>   'Trường này không được để trống',
                'sort_order.min'             =>   'Sort_order không ít hơn 3 ký tự',
                'sort_order.max'             =>   'Sort_order không vượt quá 225 ký tự',
                'sort_order.numeric'         =>   'Sort_order phải là số',
                'active.required'            =>  'Active không được trống',

            ];*/
        $validator =  Validator::make($data, [
            'name' =>'required|max:255|min:3|unique:projects',
            'description' =>'required|max:255|min:3|string',
            'is_active' =>'required',
            'sort_order'=>'required|numeric',
       ]);
        if($validator->fails()){
                return redirect()->back()->withInput($data)->withErrors($validator);
            }
        $data['user_id'] = Auth::User()->id;
          Projects::create($data);
            DB::commit();
            Session()->flash('success', 'Succsess !! Complete Add Project');
            return redirect(route('projects.index'));
        } catch(Exception $e){
            Log::info('Can not create User');
            DB::rollback();
            response()->json([
                    'error' => true,
                    'message' => 'Internal Server Error'
                ], 500);
        }

    
}

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
      $projects = Projects::find($id);
      
      return view('projects.edit',compact('projects'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
           $data = $request->all();
        unset($data['_token']);
        DB::beginTransaction();
        try{
            
        $validator =  Validator::make($data, [
            'name' =>'required|max:255|min:3|',
            'description' =>'required|max:255|min:3|string',
            'is_active' =>'required',
            'sort_order'=>'required|numeric',
       ]);
        if($validator->fails()){
                return redirect()->back()->withInput($data)->withErrors($validator);
            }
        $data['user_id'] =  1/*Auth::User()->id*/;
        
          Projects::find($id)->update($data);
          
            DB::commit();
            Session()->flash('success', 'Succsess !! Complete Edit Project');
            return Redirect(route('projects.index'));
        } catch(Exception $e){
            Log::info('Can not create User');
            DB::rollback();
            response()->json([
                    'error' => true,
                    'message' => 'Internal Server Error'
                ], 500);
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/projects/create.blade.php
@extends('layouts.index')
@section('content')
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Project Create</h3>
      </div>

      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">Go!</button>
            </span>
          </div>
        </div>

      </div>

    </div>

    <div class="clearfix"></div>
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
      @include('message.errors')
        <div class="x_panel">
          <div class="x_title">
            <h2>Projects <small>Create new a project</small></h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Settings 1</a>
                  </li>
                  <li><a href="#">Settings 2</a>
                  </li>
                </ul>
              </li>
              <li><a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <br />

            <!-- form action -->
            <form id="demo-form2" data-parsley-validate class="form-horizontal form-label-left" enctype="multipart/form-data" method="post" action="{{route('projects.store')}}">
            <input type="hidden" name="_token" value="{{csrf_token()}}">
              <!-- name -->
              <div class="form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12">Name<span class="required">*</span>
                </label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <input  type="text" id="first-name" name="name"  class="form-control col-md-7 col-xs-12">
                </div>
              </div>
              <!--/name -->
              	
              	<!-- email -->
	            <div class="form-group">
	                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Description <span class="required">*</span>
	                </label>
	                <div class="col-md-6 col-sm-6 col-xs-12">
	                  <textarea name="description" style="width: 100%;height: 110px"></textarea>
	                </div>
	            </div>
              	<!--/email -->
					
      			
      				 <!--sort_oder -->
              <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12">Sort_oder<span class="required">*</span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="number" id="first-name" name="sort_order"  class="form-control col-md-7 col-xs-12">
                  </div>
              </div>
              <!--/sort_oder -->
      				

				      <!-- group-->
	             <div class="form-group">
	                <label class="control-label col-md-3 col-sm-3 col-xs-12">Active</label>
	                <div class="col-md-6 col-sm-6 col-xs-12">
	                  <div id="gender" class="btn-group" data-toggle="buttons">
	                    <label class="btn btn-default" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
	                      <input type="radio" name="is_active" value="1"> &nbsp; Yes &nbsp;
	                    </label>
	                    <label class="btn btn-primary" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
	                      <input type="radio" name="is_active" value="0"> No
	                    </label>
	                  </div>
	                </div>
	             </div>
              	<!--/group-->
              <div class="ln_solid"></div>
              <div class="form-group">
                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                  <button type="submit" name="create" class="btn btn-success">Submit</button>
		              <button class="btn btn-primary" type="reset">Reset</button>
                  
                </div>
              </div>
            </form>
            <!-- /form action -->
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/projects/edit.blade.php
@extends('layouts.index')
@section('content')
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Project Create</h3>
      </div>

      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">Go!</button>
            </span>
          </div>
        </div>

      </div>

    </div>

    <div class="clearfix"></div>
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
      @include('message.errors')
        <div class="x_panel">
          <div class="x_title">
            <h2>Projects <small>Create new a project</small></h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Settings 1</a>
                  </li>
                  <li><a href="#">Settings 2</a>
                  </li>
                </ul>
              </li>
              <li><a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <br />

            <!-- form action -->
           {!! Form::model($projects, ['route' => ['projects.update', $projects->id], 'method' => 'PUT',
           'class' => 'form-horizontal form-label-left']) !!}
           
              <!-- name -->
              <div class="form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12">Name<span class="required">*</span>
                </label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <input  type="text" id="first-name" name="name" value="{{$projects->name}}"  class="form-control col-md-7 col-xs-12">
                </div>
              </div>
              <!--/name -->
              	
              	<!-- email -->
	            <div class="form-group">
	                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Description <span class="required">*</span>
	                </label>
	                <div class="col-md-6 col-sm-6 col-xs-12">
	                  <textarea name="description" style="width: 100%;height: 110px">
                     {{$projects->description}}</textarea>
	                </div>
	            </div>
              	<!--/email -->
					
      			
      				 <!--sort_oder -->
              <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12">Sort_oder<span class="required">*</span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="number" id="first-name" value="{{$projects->sort_order}}" name="sort_order"  class="form-control col-md-7 col-xs-12">
                  </div>
              </div>
              <!--/sort_oder -->
      				

				      <!-- group-->
	             <div class="form-group">
	                <label class="control-label col-md-3 col-sm-3 col-xs-12">Active</label>
	                <div class="col-md-6 col-sm-6 col-xs-12">
	                  <div id="gender" class="btn-group" data-toggle="buttons">
	                    <label class="btn btn-default @if($projects->is_active == 1)active @endif 
                      " data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
	                      <input type="radio" name="is_active"
                          @if($projects->is_active == 1)
                               {{'checked'}}
                                @endif 


                         value="1"> &nbsp; Yes &nbsp;
	                    </label>
	                    <label class="btn btn-primary @if($projects->is_active == 1) active @endif
                                " data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
	                      <input type="radio" name="is_active"
                        @if($projects->is_active == 0)
                                checked 
                                @endif  value="0"> No
	                    </label>
	                  </div>
	                </div>
	             </div>
              	<!--/group-->
              <div class="ln_solid"></div>
              <div class="form-group">
                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                  {{ Form::submit('Edit', ['class' => 'btn btn-default']) }}
		              <button class="btn btn-primary" type="reset">Reset</button>
                  
                </div>
              </div>
            {!! Form::close() !!}
            <!-- /form action -->
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/projects/index.blade.php
@extends('layouts.index')

@section('content')
<div class="right_col" role="main">
  <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>Project <small>List</small></h3>
        </div>

        <div class="title_right">
          <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-btn">
                <button class="btn btn-default" type="button">Go!</button>
              </span>
            </div>
          </div>
        </div>
      </div>

      <div class="clearfix"></div>
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
        @include('message.errors')
          <div class="x_panel">
            <div class="x_title">
              <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Settings 1</a>
                    </li>
                    <li><a href="#">Settings 2</a>
                    </li>
                  </ul>
                </li>
                <li><a class="close-link"><i class="fa fa-close"></i></a>
                </li>
              </ul>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">
              <table id="datatable" class="table table-striped table-bordered">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Sort_oder</th>
                    <th>Active</th>
                    <th>Users</th>
                    <th>Created_at</th>
                    <th>Update_at</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                <?php

                ?>
                   @foreach($projects as $row)
                   <tr>
                      <td>{{$row->name}}</td>
                      <td>{{$row->description}}</td>
                      <td>{{$row->sort_order}}</td>
                      <td>
                        @if($row->is_active == 1)
                            {{'Yes'}}
                        @else
                            {{'No'}}
                        @endif
                      </td>
                      <td>{{$row->User->name}}</td>
                      <td>{{$row->created_at}}</td>
                      <td>{{$row->updated_at}}</td>
                      <td>
                      {!! Form::open(['route' => ['projects.destroy',$row->id],'method' =>'DELETE']) !!}
                          {{Form::submit('Delete'),['class'=>'btn btn danger']}}
                        <a href="{{route('projects.edit',$row->id)}}">Edit</a>

                      {!! Form::close() !!}</td>
                    </tr>
                   @endforeach
                </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection