routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('trangchu',function()
{
	return view('layouts.index');
});
Route::group(['prefix'=>'/','middleware'=>'admin_login'],function()
{
	Route::resource('user','UserController');
	Route::resource('projects','ProjectController');
	
});
Route::post('login','LoginController@check');
Route::get('login','LoginController@index');
Route::get('logout','LoginController@destroy');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    // protected $table = 'users';
    protected $fillable = [
        'name','group','email', 'password','phone','sort_order',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Validator;
use DB;
use App\User;
use Log;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = User::all();
        return view('users.index',['user'=>$user]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();
        unset($data['_token']);
        DB::beginTransaction();
        try{
            $message = [
               'name.required'               =>   'Trường này không được phép để trống',
                'name.max'                   =>   'Tên không được vượt qua 255 ký tự',
                'name.min'                   =>   'Tên không ít hơn 3 ký tự',
                'email.required'             =>   'Trường email không được phép để trống',
                'email.unique'               =>   'Trường email đã tồn tại ',
                'password.required'          =>   'Trường password không được phép để trống',
                'password.min'               =>   'Trường password không được ít hơn 3 ký tự',
                'password.max'               =>   'Trường password không được vượt qua 255 ký tự',
                'phone.required'             =>   'Trường phone không được phép để trống',
                'phone.min'                  =>   'Phone không ít hơn 3 ký tự',
                'phone.max'                  =>   'Phone không vượt quá 15 ký tự',
                'sort_order.required'        =>   'Trường này không được để trống',
                
            ];
            $validator =  Validator::make($data, [
                'name'          =>  'required|min:3|max:255',
                'email'         =>  'required|unique:users,email|max:255|email',
                'password'      =>  'required|min:3|max:255',
                'phone'         =>  'required|min:3|max:15',
                'sort_order'   =>   'required',
            ],$message);
            if($validator->fails()){
                return redirect()->back()->withInput($data)->withErrors($validator);
            }
            $data['password'] = bcrypt($request->password);
            User::create($data);
            DB::commit();
            Session()->flash('success', 'Succsess !! Complete Add Project');
            return Redirect(url('user'));
        } catch(Exception $e){
            DB::rollback();
            response()->json([
                    'error' => true,
                    'message' => 'Internal Server Error'
                ], 500);
        }
    }
    
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user =  User::find($id);
        return view('users.edit',['user'=>$user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();
        unset($data['_token']);
        DB::beginTransaction();
        try{
            $message = [
                'name.required'               =>   'Trường này không được phép để trống',
                'name.max'                   =>   'Tên không được vượt qua 255 ký tự',
                'name.min'                   =>   'Tên không ít hơn 3 ký tự',
                'email.required'             =>   'Trường email không được phép để trống',
                'password.required'          =>   'Trường password không được phép để trống',
                'password.min'               =>   'Trường password không được ít hơn 3 ký tự',
                'password.max'               =>   'Trường password không được vượt qua 255 ký tự',
                'phone.required'             =>   'Trường phone không được phép để trống',
                'phone.min'                  =>   'Phone không ít hơn 3 ký tự',
                'phone.max'                  =>   'Phone không vượt quá 15 ký tự',
                'sort_order.required'        =>   'Trường này không được để trống',
                'sort_order.max'             =>   'Sort_order không vượt quá 225 ký tự',
            ];
            $validator =  Validator::make($data, [
                'name'          =>  'required|min:3|max:255',
                'email'         =>  'required|max:255|email',
                'password'      =>  'required|min:3|max:255',
                'phone'         =>  'required|min:3|max:15',
                'sort_order'   =>   'required|max:15',
            ],$message);
            if($validator->fails())
            {
                return redirect()->back()->withInput($data)->withErrors($validator);
            }
            $user = User::find($id)->update($data);;
            DB::commit();
            Session()->flash('success', 'Succsess !! Complete Add Project');
            return redirect(url('user'));
        } catch(Exception $e){
            Log::info('sua không thành công');
            DB::rollback();
            response()->json([
                    'error' => true,
                    'message' => 'Internal Server Error'
                ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();
        return redirect(url('user'))->with('thongbao','Xóa thành công');

    }
   

}

resources/views/users/create.blade.php
@extends('layouts.index')
@section('content')
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>User Create</h3>
      </div>
      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">Go!</button>
            </span>
          </div>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
      @include('message.errors')
        <div class="x_panel">
          <div class="x_title">
            <h2>User<small>Create new account user</small></h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Settings 1</a>
                  </li>
                  <li><a href="#">Settings 2</a>
                  </li>
                </ul>
              </li>
              <li><a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <br />
            <!-- form action -->
            <form id="demo-form2" data-parsley-validate class="form-horizontal form-label-left" enctype="multipart/form-data" method="post" action="{{route('user.store')}}">
            <input type="hidden" name="_token" value="{{csrf_token()}}">
              <!-- name -->
              <div class="form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12">Name<span class="required">*</span>
                </label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <input  type="text" id="first-name" name="name" required="required" class="form-control col-md-7 col-xs-12">
                </div>
                 
              </div>
              <!--/name -->
              	
              	<!-- email -->
	            <div class="form-group">
	                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Email <span class="required">*</span>
	                </label>
	                <div class="col-md-6 col-sm-6 col-xs-12">
	                  <input type="email"  id="last-name" name="email" required="required" class="form-control col-md-7 col-xs-12">
	                </div>
	            </div>
              	<!--/email -->
					
      				<!-- password -->
      				      <div class="form-group">
      	                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Password <span class="required">*</span>
      	                </label>
      	                <div class="col-md-6 col-sm-6 col-xs-12">
      	                  <input type="password"  id="last-name" name="password" required="required" class="form-control col-md-7 col-xs-12">
      	                </div>
      	            </div>
      				<!--/password -->

				      <!-- group-->
	             <div class="form-group">
	                <label class="control-label col-md-3 col-sm-3 col-xs-12">Group</label>
	                <div class="col-md-6 col-sm-6 col-xs-12">
	                  <div id="gender" class="btn-group" data-toggle="buttons">
	                    <label class="btn btn-default" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
	                      <input type="radio" name="group" value="1"> &nbsp; Parent &nbsp;
	                    </label>
	                    <label class="btn btn-primary" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
	                      <input type="radio" checked="checked" name="group" value="0"> Children
	                    </label>
	                  </div>
	                </div>
	             </div>
              	<!--/group-->

	            <!--sort_oder -->
	            <div class="form-group">
	                <label class="control-label col-md-3 col-sm-3 col-xs-12" name="name" >Sort_oder<span class="required">*</span>
	                </label>
	                <div class="col-md-6 col-sm-6 col-xs-12">
	                  <input type="number" id="first-name" name="sort_order" required="required" class="form-control col-md-7 col-xs-12">
	                </div>
	            </div>
	            <!--/sort_oder -->
              	

				<!-- phone-->
				      <div class="form-group">
	                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Phone <span class="required">*</span>
	                </label>
	                <div class="col-md-6 col-sm-6 col-xs-12">
	                  <input type="nubmer"  id="last-name" name="phone" required="required" class="form-control col-md-7 col-xs-12">
	                </div>
	            </div>

				<!--/phone -->

              <div class="ln_solid"></div>
              <div class="form-group">
                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
		              <button class="btn btn-primary" type="reset">Reset</button>
                  <button type="submit" name="create" class="btn btn-success">Submit</button>
                </div>
              </div>
            </form>
            <!-- /form action -->
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.index')
@section('content')
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>User</h3>
      </div>
      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">Go!</button>
            </span>
          </div>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
      @include('message.errors')
        <div class="x_panel">
          <div class="x_title">
            <h2>User<small>Edit a acount user</small></h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Settings 1</a>
                  </li>
                  <li><a href="#">Settings 2</a>
                  </li>
                </ul>
              </li>
              <li><a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <br />
            
            <!-- form action -->
            {!! Form::model($user, ['route' => ['user.update', $user->id], 'method' => 'PUT',
           'class' => 'form-horizontal form-label-left']) !!}
                <input type="hidden" name="_token" value="{{csrf_token()}}">

                  <!-- name -->
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Name<span class="required">*</span>
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <input value="{{$user->name}}"  type="text" id="first-name" name="name" required="required" class="form-control col-md-7 col-xs-12">
                    </div>
                     <p class="font-red-mint">{{ $errors->first('name') }}</p>
                  </div>
                  <!--/name -->
                  	
                  	<!-- email -->
    	            <div class="form-group">
    	                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Email <span class="required">*</span>
    	                </label>
    	                <div class="col-md-6 col-sm-6 col-xs-12">
    	                  <input type="email" value="{{$user->email}}" id="last-name" name="email" required="required" class="form-control col-md-7 col-xs-12">
    	                </div>
                       <p class="font-red-mint">{{ $errors->first('email') }}</p>
    	            </div>
                  	<!--/email -->
    					
          				<!-- password -->
          				      <div class="form-group">
          	                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Password <span class="required">*</span>
          	                </label>
          	                <div class="col-md-6 col-sm-6 col-xs-12">
          	                  <input type="password" value="{{$user->password }}" id="last-name" name="password" required="required" class="form-control col-md-7 col-xs-12">
          	                </div>
                             <p class="font-red-mint">{{ $errors->first('password') }}</p>
          	            </div>
          				<!--/password -->

    				      <!-- group-->
    	             <div class="form-group">
    	                <label class="control-label col-md-3 col-sm-3 col-xs-12">Group</label>
    	                <div class="col-md-6 col-sm-6 col-xs-12">
    	                  <div id="gender" class="btn-group" data-toggle="buttons">
    	                    <label class="btn btn-default" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
    	                      <input  
                            @if($user->group == 1)
                              {{"checked='checked'"}}
                            @endif
                            type="radio" name="group" value="1"> &nbsp; Parent &nbsp;
    	                    </label>
    	                    <label class="btn btn-primary" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
    	                      <input
                            @if($user->group == 0)
                              {{"checked='checked'"}}
                            @endif
                             type="radio" name="group" value="0"> Children
    	                    </label>
    	                  </div>
    	                </div>
    	             </div>
                  	<!--/group-->

    	            <!--sort_oder -->
    	            <div class="form-group">
    	                <label class="control-label col-md-3 col-sm-3 col-xs-12" name="name" >Sort_order<span class="required">*</span>
    	                </label>
    	                <div class="col-md-6 col-sm-6 col-xs-12">
    	                  <input value="{{$user->sort_order }}" type="number" id="first-name" name="sort_order" required="required" class="form-control col-md-7 col-xs-12">
    	                </div>
                       <p class="font-red-mint">{{ $errors->first('sort_oder') }}</p>
    	            </div>
    	            <!--/sort_oder -->
                  	

    				<!-- phone-->
    				      <div class="form-group">
    	                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Phone <span class="required">*</span>
    	                </label>
    	                <div class="col-md-6 col-sm-6 col-xs-12">
    	                  <input value="{{$user->phone}}" type="text" pattern=".{1,15}" id="last-name" name="phone" required="required" class="form-control col-md-7 col-xs-12">
    	                </div>
                       <p class="font-red-mint">{{ $errors->first('phone') }}</p>
    	            </div>

    				<!--/phone -->

                  <div class="ln_solid"></div>
                  <div class="form-group">
                    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                    <button class="btn btn-primary" type="reset">Reset</button>
    		            {{ Form::submit('Edit', ['class' => 'btn btn-default']) }}
                    </div>
                  </div>
             
            <!-- /form action -->
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.index')

@section('content')
<div class="right_col" role="main">
  <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>Cates <small>List</small></h3>
        </div>

        <div class="title_right">
          <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-btn">
                <button class="btn btn-default" type="button">Go!</button>
              </span>
            </div>
          </div>
        </div>
      </div>

      <div class="clearfix"></div>
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
        @include('message.errors')
          <div class="x_panel">
            <div class="x_title">
              <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Settings 1</a>
                    </li>
                    <li><a href="#">Settings 2</a>
                    </li>
                  </ul>
                </li>
                <li><a class="close-link"><i class="fa fa-close"></i></a>
                </li>
              </ul>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">
              <table id="datatable" class="table table-striped table-bordered">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Sort_oder</th>
                    <th>Group</th>
                    <th>Phone</th>
                    <th>Created_at</th>
                    <th>Update_at</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach($user as $u)
                    <tr>
                      <td>{{$u->name}}</td>
                      <td>{{$u->email}}</td>
                      <td>{{$u->sort_order}}</td>
                      <td>
                        @if($u->group == 0)
                          {{'user'}}
                        @elseif($u->group ==1)
                          {{'admin'}}
                        @endif
                      </td>
                      <td>{{$u->phone}}</td>
                      <td>{{$u->created_at}}</td>
                      <td>{{$u->updated_at}}</td>

                      @if(Auth::user()->group == 1 && $u->group == Auth::user()->group  ) 
                        <td>

                        <a href="{{route('user.edit',$u->id)}}" class="btn btn danger">
                          <span>Edit</span>
                        </a>
                        {!! Form::open(['route' => ['user.destroy',$u->id],'method' =>'DELETE']) !!}
                          {{Form::submit('Delete'),['class'=>'btn btn danger']}}
                        {!! Form::close() !!}
                        </td>
                      @else
                        <td>
                          <p> no action</p>
                        </td>
                      @endif 

                    </tr>
                  @endforeach
                </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection